In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np.__version__

'2.0.1'

In [3]:
print("NumPy version:", np.__version__)

NumPy version: 2.0.1


In [4]:
#Prove NumPy is fasted than List:
import time

#Creating large list and Array:
python_list=list(range(1000000))
numpy_array=np.arange(1000000)

#Time elements-wise operation
start=time.time()
result_list=[x*2 for x in python_list]
print("Python list time:" ,time.time()-start,"seconds")

start=time.time()
result_array=numpy_array*2
print("NumPy array time:", time.time()-start,"seconds")

#Memory efficiency:
print("Python list size:", python_list.__sizeof__(),"bytes")
print("NumpPy array size:",numpy_array.nbytes,"bytes")

Python list time: 0.033537864685058594 seconds
NumPy array time: 0.0020008087158203125 seconds
Python list size: 8000040 bytes
NumpPy array size: 8000000 bytes


In [5]:
import numpy as np
li =[3,4,5]
print(type(li))
arr = np.array([1, 2, 3, 4, 5])
type(arr)

<class 'list'>


numpy.ndarray

In [6]:
#NumPy array is a grid of values, all of the same type
arr=np.array([1,2,3,4,5])
print("1D arrar:",arr)

1D arrar: [1 2 3 4 5]


In [7]:
#Python list:
py_list=[1, 2, 3, 4, 5]
print("Python List:",py_list)

Python List: [1, 2, 3, 4, 5]


In [8]:
#2D array:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\n 2D Array :\n",arr_2d)


 2D Array :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#How to create a numpy array from python list:
list_1d=[1,2,3,4,5]
list_2d=[[1,2,3,4],[5,6,7,8]]
array_1d=np.array(list_1d)
array_2d=np.array(list_2d)
print("1D array:",array_1d)
print("\n2D array: \n",array_2d)

1D array: [1 2 3 4 5]

2D array: 
 [[1 2 3 4]
 [5 6 7 8]]


In [10]:
#Basic array operations:
a=np.array([1, 2, 3])
a.dtype 

dtype('int64')

In [11]:
a

array([1, 2, 3])

In [12]:
#Arrays with different data types:
int_array = np.array([1, 2, 3], dtype=np.int32)
print("Integer array:", int_array, "Dtype:", int_array.dtype)

Integer array: [1 2 3] Dtype: int32


In [13]:
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("Float array:", float_array, "Dtype:", float_array.dtype)

Float array: [1. 2. 3.] Dtype: float64


In [14]:
bool_array = np.array([True, False, True], dtype=np.bool_)
print("Boolean array:", bool_array, "Dtype:", bool_array.dtype)

Boolean array: [ True False  True] Dtype: bool


In [15]:
string_array = np.array(['apple', 'banana', 'cherry'], dtype=np.str_)
print("String array:", string_array, "Dtype:", string_array.dtype)

String array: ['apple' 'banana' 'cherry'] Dtype: <U6


In [16]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [17]:
#Elementwise addition in list:
a=[1,2,3]
b=[4,5,6]
result=[]
for i in range(len(a)):
    for j in range(len(b)):
        if i==j:
            result.append(a[i]+b[j])
print(result)

[5, 7, 9]


In [18]:
#Elementwise addition using array:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [19]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [20]:
print("Subraction:",a-b)
print("Multiplication:",a*b)
print("Division:",b/a)
print("Modulus:",b%a)
print("Square of a:",a**2)

Subraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Modulus: [0 1 0]
Square of a: [1 4 9]


In [21]:
a=[1,2,3]
a*8

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [23]:
#Scalar operations:
print("Scalar addition:",a+10)
print("Scalar Multiplication:",a*2)

Scalar addition: [11 12 13]
Scalar Multiplication: [2 4 6]


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Sum:",np.sum(arr))

Sum: 45


In [25]:
print("Mean:",np.mean(arr))

Mean: 5.0


In [26]:
print("Standard Deviation:",np.std(arr))

Standard Deviation: 2.581988897471611


In [27]:
print("Maximum:",np.max(arr))

Maximum: 9


In [28]:
print("Minimum:",np.min(arr))

Minimum: 1


In [29]:
print("Index of max:",np.argmax(arr))

Index of max: 8


In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#Logical operations(np.all() & np.any())
print("\nAll positive?",np.all(arr>0))
print("Any greater than 4?",np.any(arr>4))


All positive? True
Any greater than 4? True


In [32]:
#Array attributes:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print("\nShape:",arr.shape)


Shape: (3, 3)


In [34]:
print("Size:",arr.size)

Size: 9


In [35]:
print("Number of dimensions:",arr.ndim)

Number of dimensions: 2


In [36]:
print("Data Type:", arr.dtype)

Data Type: int64


In [37]:
#Range() functions:
range_arr=np.arange(0,10,2)
print("Range array:",range_arr)

Range array: [0 2 4 6 8]


In [38]:
linspace=np.linspace(0,1,5)
print("Linearly spaced array:",linspace)

Linearly spaced array: [0.   0.25 0.5  0.75 1.  ]


In [39]:
#Adding elements:
arr=np.array([1,2,3])
print("Original array:",arr)

Original array: [1 2 3]


In [40]:
#adding new array:
arr_appended=np.append(arr,[4,5])
print("After append:",arr_appended)

After append: [1 2 3 4 5]


In [41]:
#inserting new array using index:
arr_inserted = np.insert(arr,0,[10,20])
print("After insert:",arr_inserted)

After insert: [10 20  1  2  3]


In [42]:
#Removing elements
arr_removed = np.delete(arr, [0])  # indices to remove
print("\nAfter delete:", arr_removed)


After delete: [2 3]


In [43]:
arr

array([1, 2, 3])

In [44]:
#Sorting:
unsorted=np.array([3,1,4,2,5])
sorted_arr=np.sort(unsorted)
print("\nSorted array:",sorted_arr)


Sorted array: [1 2 3 4 5]


In [45]:
unsorted.sort()
print("In-place sorted:",unsorted)

In-place sorted: [1 2 3 4 5]


In [46]:
#Sorting 2D arrays:
arr_2d=np.array([[3,2,9],[2,5,4]])
print("2D array before sorting:\n", arr_2d)
print("Sorting along rows:\n",np.sort(arr_2d,axis=1))
print("Sorted along columns:\n",np.sort(arr_2d,axis=0))

2D array before sorting:
 [[3 2 9]
 [2 5 4]]
Sorting along rows:
 [[2 3 9]
 [2 4 5]]
Sorted along columns:
 [[2 2 4]
 [3 5 9]]


In [47]:
#3D Array:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Array:\n",arr)

Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
arr.shape

(2, 2, 3)

In [49]:
arr.size

12

In [50]:
arr.ndim

3

In [51]:
len(arr)

2

In [52]:
#Reshape an array:
import numpy as np
arr=np.arange(12)
print("Original array (1D):",arr)

Original array (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
#Reshape to 2D:
arr_2d=arr.reshape(2,6)
print("\nReshaped to 3×4 :\n",arr_2d)


Reshaped to 3×4 :
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
#Reshape to 3D:
arr_3D=arr.reshape(2,3,2)
print("\nReshaped to 2×3×2:\n",arr_3D)


Reshaped to 2×3×2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [55]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [56]:
#Reshape requires same total size
try:
    arr.reshape(3,4)
    print("\nReshape to (3,4) successful")
    arr.reshape(2,5)
except ValueError as e:
    print("\nCannot reshape:",e)


Reshape to (3,4) successful

Cannot reshape: cannot reshape array of size 12 into shape (2,5)


In [57]:
arr_2d.reshape(-1) #doesn't affect the original array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
#Automatic dimension with -1:
arr_auto=arr.reshape(2,-1)
print("\nAuto Shaped to 2,6:\n",arr_auto)


Auto Shaped to 2,6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [60]:
#Deep copy:
arr_copy=arr.copy()
arr_copy.resize(5,3,refcheck=False)
print("\n Resized to 5×3 (padding with zeros):\n",arr_copy)


 Resized to 5×3 (padding with zeros):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  0  0]]


In [61]:
arr_3d_resize = arr.resize(2, 3, 2)
print("\nREsizedArray: \n ",arr_3d_resize)
print("\nREsizedArray: \n ",arr)


REsizedArray: 
  None

REsizedArray: 
  [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [62]:
arr_2=np.arange(12).reshape(3,4)
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
#Flatten back to 1D:
arr_ravel=arr_2.ravel()
print("\nFlattened array:",arr_ravel)


Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [64]:
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
arr_ravel[0]=1 #affects the original array
arr_ravel

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
arr_2

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
arr_3=np.arange(12).reshape(3,4)
arr_3
arr_flat=arr_3.flatten()
print("Flattened array :",arr_flat)

Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
arr_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
arr_flat[0]=2000
arr_flat

array([2000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [70]:
arr_3 #doesns't affect the original array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
#Flattening:
arr=np.array([[1,2,3],[4,5,6]])
print("Original array(2×3):\n",arr)
print("Flattening (row_major):",arr.flatten())
print("Flattening(column major):",arr.flatten('F'))

print("\nRaveled:",arr.ravel('F'))

Original array(2×3):
 [[1 2 3]
 [4 5 6]]
Flattening (row_major): [1 2 3 4 5 6]
Flattening(column major): [1 4 2 5 3 6]

Raveled: [1 4 2 5 3 6]


In [72]:
#Indexing and Slicing:

arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[6:]

array([6, 7, 8, 9])

In [74]:
arr[-1:-6:-1]

array([9, 8, 7, 6, 5])

In [75]:
arr[:5:-1]

array([9, 8, 7, 6])

In [76]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
#1D array indexing:
arr=np.arange(10)
print("Array:",arr)
print("First element:",arr[0])
print("Last element:",arr[-1])
print("Slice from index 2 to 5:", arr[2:5])
print("Ever other element:",arr[::2])
print("Reversed array:",arr[::-1])

Array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Slice from index 2 to 5: [2 3 4]
Ever other element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [78]:
#2D Array indexing:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D array:\n",arr_2d)    


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
print("Element at row 1, column 2:", arr_2d[1,2])

Element at row 1, column 2: 6


In [80]:
print("First row:",arr_2d[0,:])

First row: [1 2 3]


In [81]:
print("Lat Column:",arr_2d[:,-1])

Lat Column: [3 6 9]


In [82]:
print("Sub-matrix (first two rows, last two columns):\n",arr_2d[:2,1:])

Sub-matrix (first two rows, last two columns):
 [[2 3]
 [5 6]]


In [83]:
print("\nElements greater than 5:", arr_2d[arr_2d > 5])


Elements greater than 5: [6 7 8 9]


In [84]:
print("Elements at positions [0,2] and [2,0]:", arr_2d[[0, 2], [2, 0]])

Elements at positions [0,2] and [2,0]: [3 7]


In [85]:
#Broadcasting:
arr=np.array([1,2,3])
print("Array + Scalar:", arr+5)

Array + Scalar: [6 7 8]


In [86]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
b=np.array([[10,20,30]])
b

array([[10, 20, 30]])

In [88]:
matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
vector=np.array([10,20,30])
print("\nMatrix +vector :\n",matrix+vector)


Matrix +vector :
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [89]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
vector=np.array([10,20,30,40])
print("\nMatrix +vector :\n",matrix +vector)

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [94]:
try:
    matrix=np.array([[1,2,3],[4,5,6]])
    vector=np.array([10,20])
    print("\nMatrix +vector :\n",matrix +vector)
except ValueError as e:
    print("\nBroadcasting error:",e)
vector_reshaped=vector.reshape(2,1)
print("\nMatrix + reshaped vector:\n",matrix + vector_reshaped)


Broadcasting error: operands could not be broadcast together with shapes (2,3) (2,) 

Matrix + reshaped vector:
 [[11 12 13]
 [24 25 26]]


In [97]:
#Creating Matrices
#Zero matrix:
zero_matrix=np.zeros((3,3))
print("From list:\n", zero_matrix)

From list:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [98]:
#One matrix:
ones_matrix = np.ones((2,4))
print("\n Ones matrix:\n", ones_matrix)


 Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [99]:
identity_matrix = np.eye(3)
print("\nIdentity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [101]:
diagonal_matrix = np.diag([1,2,3,4,5])
print("\nDiagonalMatrix: \n", diagonal_matrix)


DiagonalMatrix: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [102]:
#Random Matrix:(0-1 values)
random_matrix=np.random.random((3,4))
print("\nRandom Matrix\n", random_matrix)


Random Matrix
 [[0.6495545  0.36942908 0.33996667 0.10658719]
 [0.68364136 0.82439356 0.21285233 0.3151696 ]
 [0.76845073 0.19437373 0.70138141 0.28188981]]


In [104]:
#Matrix Multiplication:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [105]:
#Matrix addition:
print("\n Matrix addition:\n",a+b)


 Matrix addition:
 [[ 6  8]
 [10 12]]


In [106]:
#Multiplication:
print("\nMatrix multiplication:\n",np.matmul(a,b))


Matrix multiplication:
 [[19 22]
 [43 50]]


In [107]:
print("\n Dot product(multiplication)\n",np.dot(a,b))


 Dot product(multiplication)
 [[19 22]
 [43 50]]


In [110]:
print("\nMatrix multiplication:\n",a@b)


Matrix multiplication:
 [[19 22]
 [43 50]]


In [111]:
print("\nElement wise multiplication:\n",a*b)


Element wise multiplication:
 [[ 5 12]
 [21 32]]


In [123]:
print("\nMatrix Transpose:\n",a.T)


Matrix Transpose:
 [[1 3]
 [2 4]]


In [124]:
#Generating Random numbers:
np.random.seed(9)

In [125]:
np.random.random(1)

array([0.01037415])

In [129]:
#Random number generation
print("Random float[0,2):",np.random.random())

Random float[0,2): 0.31622430788063316


In [127]:
print("Random interger [0,10):",np.random.randint(10))

Random interger [0,10): 6


In [130]:
#Array of random numbers:
print("\n3 random floats:",np.random.random(3))


3 random floats: [0.01332201 0.87722121 0.13752682]


In [132]:
print("2×3 random floats:\n",np.random.random((2,3)))

2×3 random floats:
 [[0.13861328 0.39588585 0.49465452]
 [0.31570887 0.37395118 0.73465804]]


In [133]:
print("5 random integers[1,100):",np.random.randint(1,100,5))

5 random integers[1,100): [75 57 94 63 13]
